### ISSUE TITLE
bad enrichment lim => l of im

### ISSUE THREAD

**Issue by pkra** [zorkow/speech-rule-engine#451] opened 2021-02-04 14:13 UTC
I couldn't reproduce a smaller sample but this (bad authoring) leads to bad enrichment (impacting visual rendering).

`M(t) =\mathop {\mathrm{lim}} \limits _\leftarrow M`

will get a function application between `l` and `im` which is also visible in output

![image](https://user-images.githubusercontent.com/426686/106904373-673ff000-66fb-11eb-9caf-b692ad9702a0.png)

**Comment by davidfarmer** [comment] 2021-02-04 14:35
Is that an "inverse limit"?  If so, the pronunciation may be wrong
even if the typesetting is correct.

**Comment by zorkow** [comment] 2021-02-04 16:35
Interesting. SRE propagates the knowledge that `M` is a simple function, and for some reason then decides that `l` is one as well.

There's a couple of problems I can see:
1. The poor LaTeX leads to `lim` being split into three identifiers, `l` `i` `m`.
2. SRE can not interpret that as a single operator. Of course using `\lim` would help. (Or MathJax not taking it apart, but that is a different discussion that is currently going on between @dpvc and  David Jones.)
3. SRE should interpret this as juxtaposition of three letters, but for some bizarre reason it takes `l` to be a function.
4. @davidfarmer at the moment SRE does not even see the limit and can therefore also not make any guess on what the modifier could mean. But at least it should be something like `Modifying below limit with left arrow`.

**Comment by zorkow** [comment] 2021-02-04 16:36
> Is that an "inverse limit"? If so, the pronunciation may be wrong even if the typesetting is correct.

I vaguely recall having a professor that used left arrow to mean going to -\infty. But that was of course on a blackboard and out of laziness.

**Comment by pkra** [comment] 2021-02-08 20:21
> 3. SRE should interpret this as juxtaposition of three letters, but for some bizarre reason it takes l to be a function.

Does this mean this might be fixable? (Of course, I would not mind if this example can be used to argue in favor of MathJax not breaking things up in the first place but only if it actually happens.)

**Comment by pkra** [comment] 2021-03-12 13:17
Here's a new case using the locale fr with the latest beta:

 \mathrm{Hom}_{L[\check{G}]} \big (\mathrm{JL}(M), L\otimes _{\mathbf{Q}_p}\mathscr{O}({{\cal M}_\infty })\big )^{\mathscr{G}_F},

where I get "H majuscule o en normal m en normal ..."

Visually:

![image](https://user-images.githubusercontent.com/426686/110945144-a0dcca00-833d-11eb-8174-fa17110e2e41.png)


@zorkow should I create a separate issue?

**Comment by zorkow** [comment] 2021-03-12 15:29
I can't reproduce this. Is that using enrichment from MathJax?
What I do note, however, is that there is no mapping for the caron. But that is a duplicate of #274

**Comment by zorkow** [comment] 2021-03-12 17:59
I can't reproduce that using enrichment with deep speech either.

**Comment by pkra** [comment] 2021-03-12 20:19
It's my usual workflow using "my" amermathsoc branch together with the latest beta, doing tex => sre => svg separately.

**Comment by zorkow** [comment] 2021-03-28 01:53
I can't see that issue anymore. Try again with the latest beta version.

**Closed** 2021-04-19 00:23 UTC
Labels: bug, fixed
